### ISSUE TITLE
使用雲端資料庫的問題

### ISSUE THREAD

**Issue by lmly9193** [reanox/MapleStory-v113-Server-Eimulator#14]
![](http://i.imgur.com/jkyaB9J.png)
reanox你好
若把 MySQL 資料庫放在雲端會造成上圖所示無法繼續，請問有解決方法嗎？

**Comment by reanox** [comment]
若是有顯示該圖示訊息，並非是MySQL問題

**Comment by lmly9193** [comment]
上面的問題已經解決了，因為載入時間(約七八分鐘)很長讓我誤以為出錯。
我嘗試架設了一個基於 CentOS 的伺服器，而 MSServer 運行良好，但是客戶端在登入畫面會馬上閃退。
另外還有幾個問題也苦無對策，比如說結束客戶端時鍵盤和滑鼠會失靈，不清楚這是 Win10 相容性問題還是客戶端 Bug。
