### ISSUE TITLE
關於登入

### ISSUE THREAD

**Issue by JosephTien** [reanox/MapleStory-v113-Server-Eimulator#17]
嗨狐大：
wz檔什麼的我都準備好了，server也都架設好了，但唯獨找不到自連登入的辦法，能否提供一下登入器或登入的辦法呢?

**Comment by reanox** [comment]
MapleStory.exe 127.0.0.1 8484

**Comment by JosephTien** [comment]
就在稍早突然開竅成功了，謝謝。
不過雖然目前已經成功架設，卻有些擔心我的wz和大大的不合，因為若用wzrepacker把我的wz dump成xml，開服吃資料的時候會噴error，所以只好在client端用我的wz，而server端用大大提供的xml。
不曉得能否問一下大大的客戶端的來源？：）

**Comment by JosephTien** [comment]
另外我發現調整倍率沒有效果，不曉得是否是我個人的問題？

**Comment by reanox** [comment]
乾淨版本客戶端
