### ISSUE TITLE
召喚獸問題

### ISSUE THREAD

**Issue by asdlkis** [reanox/MapleStory-v113-Server-Eimulator#19]
不好意思 大大我想請問一下
我的職業召喚獸一旦召喚之後 在召喚地圖攻擊怪物會死亡(是有傷害數字的)
但是到下一張地圖 召喚獸攻擊怪物不會死亡 (是有傷害數字的)
想請問一下 我該到哪邊修復??

**Comment by reanox** [comment]
https://github.com/reanox/MapleStory-v113-Server-Eimulator/commit/4487b5a389d28566ec6a36f668d1ce7bae93aed0

已修復
