### ISSUE TITLE
商城問題[已修復]

### ISSUE THREAD

**Issue by wonforyou** [reanox/MapleStory-v113-Server-Eimulator#23]
更新架構後點商城會換頻道
不會進入商城內

**Comment by wonforyou** [comment]
補充一下 也不能換頻

**Comment by reanox** [comment]
https://github.com/reanox/MapleStory-v113-Server-Eimulator/commit/b48dd4bcd0e0bff915d548496610ba146f9dab07
已修正

**Comment by HuyaJuri** [comment]
10/21 下載下來無法進入商城

**Comment by reanox** [comment]
Release 版本無修正，請自行編譯

**Comment by reanox** [comment]
https://github.com/reanox/MapleStory-v113-Server-Simulator/releases/tag/v3.1
修復版本

從 Windows 10 的郵件<https://go.microsoft.com/fwlink/?LinkId=550986>傳送

________________________________

**Comment by sdws1027** [comment]
狐大大請問一下，我商城也遇到一樣的問題，頻道也永遠在1頻，我整個檔案重新下載再識一次嗎？那請問你上面的修復版本跟現在全部的檔案哪個是最新版的呢？
