### ISSUE TITLE
SQL問題

### ISSUE THREAD

**Issue by sam0324sam** [reanox/MapleStory-v113-Server-Eimulator#4]
您好，我在初次架設時匯入SQL出現了一些問題
是因為我使用的是mariaDB的關西嗎?有沒有甚麼解決方法呢?謝謝白狐大!

> [Err] 1075 - Incorrect table definition; there can be only one auto column and it must be defined as a key
[Err] --
-- 使用資料表 AUTO_INCREMENT `hiredfishing`
--
ALTER TABLE `hiredfishing`
  MODIFY `PackageId` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;
[Msg] Finished - Unsuccessfully

**Comment by reanox** [comment]
待我測試更新

**Comment by sam0324sam** [comment]
不好意思 這次變成這個了

> [Err] 1068 - Multiple primary key defined
[Err] --
-- 資料表索引 `hiredmerch`
--
ALTER TABLE `hiredmerch`
  ADD PRIMARY KEY (`PackageId`);
[Msg] Finished - Unsuccessfully

**Comment by reanox** [comment]
已修正
