### ISSUE TITLE
您好,想請問您SQL以及釣魚問題

### ISSUE THREAD

**Issue by jp05935611** [reanox/MapleStory-v113-Server-Eimulator#6]
您好，謝謝您的分享，我有個問題想要請教，我在使用SQL匯入的時候都會發生utf8mb4的錯誤，而後導入也都會有錯誤，想請問是否資料庫要設定呢？

另外我跟著您的方法編譯釣魚修復，NPC已經可以正確回話了但是使用精靈釣手還是不會跑出來釣魚，請問是有哪邊漏掉的嗎？希望大大能給點提示 謝謝

**Comment by reanox** [comment]
包頭文件請做修正

**Comment by jp05935611** [comment]
謝謝您~!

那請問精靈小釣手沒有出現的問題可以從哪邊著手嗎？ 會是SQL的問題嗎？
因為後來有新增一些東西編譯都有出來 應該不是jar沒替換

**Comment by reanox** [comment]
OpCode要修正

**Comment by reanox** [comment]
Libs/opcode/recv.ini

**Comment by jp05935611** [comment]
因為我翻了一下您的內容好像沒有RECV要修正的項，請問前輩可以提示要加什麼樣的東西嗎~?

**Comment by reanox** [comment]
那你一定沒翻仔細喔...

**Comment by jp05935611** [comment]
!真的嗎~ 不好意思 
因為我看精靈小釣手修復的相關只有改到send，recv最近的修改是在月光寶盒那邊
我有去看src的recvpacketopcode 裡面有一串 //USE_FISHING, // Some unknown value sent by client after fishing for 30 sec, ignored ，請問是跟他有關係嗎...
抱歉一直請教您

**Comment by amyloveqaz** [comment]
白狐大大 ! 我recv.ini看著也有改了 也重新下載過了 還是無法成功呢 ! 不知道是哪邊出問題 
提醒樓主一下 某個文件看清楚按進去第一個就是了 Libs/opcode/send.ini

**Comment by jp05935611** [comment]
謝謝您，但我send.ini有更改 只是我找不到recv.ini要改的東西，難道是一樣的？！

不好意思剛接觸所以會有這種問題..

**Comment by gems9487** [comment]
OpCode要修正

**Comment by reanox** [comment]
USE_HIRED_MERCHANT
下面多一個
USE_HIRED_FISHING = 0x39

**Comment by jp05935611** [comment]
謝謝前輩！ 抱歉一直打擾您~
