### ISSUE TITLE
想請教白狐大一個問題

### ISSUE THREAD

**Issue by kkkk147258** [reanox/MapleStory-v113-Server-Eimulator#8]
http://i.imgur.com/xM2fIo2.jpg

原本都可以開啟，但今天要開啟卻什麼都沒東西了！

sql可以透過管理程式察看跟連接，服務也有啟動。

請問白狐大這可能是哪方面的問題呢?

**Comment by reanox** [comment]
查看有沒有更動到連線資料吧，沒有任何反應通常都是連不上SQL的問題
